apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::777653593714:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-6KZICtvIVIeR
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - default-trainee
      userarn: arn:aws:iam::777653593714:user/Ramesh
      username: Ramesh      
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-02T23:28:32Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1157"
  uid: b6a498a7-cd38-4513-877b-99a927b7d39a
