apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::777653593714:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-8Olh9wqENLza
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - default-trainee
      userarn: arn:aws:iam::777653593714:user/suresh
      username: suresh
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-01T22:32:42Z"
  name: aws-auth
  namespace: kube-system
  uid: 6933ad36-b383-4fd4-a709-2bf16a8dc625
